import os
import json
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, Request
from fastapi.responses import PlainTextResponse
from telegram import Update
from telegram.ext import Application, MessageHandler, ContextTypes, filters

app = FastAPI()

BOT_TOKEN = os.environ.get("BOT_TOKEN")

# Public log file generated by the running service.
LOG_FILE = "run.jsonl"


def write_log(message: str, answer):
    record = {
        "run_id": str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "question": message,
        "answer": answer,
    }

    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


async def solve_question(question: str):
    """
    Temporary solver.

    We will replace this with the actual data-analysis agent
    after the Telegram/deployment pipeline is working.
    """

    return {
        "message": "Agent received the question",
        "question": question
    }


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not update.message or not update.message.text:
        return

    question = update.message.text

    answer = await solve_question(question)

    write_log(question, answer)

    response = {
        "answer": answer,
        "log_url": "https://YOUR-DEPLOYED-URL/run.jsonl"
    }

    await update.message.reply_text(
        json.dumps(response, ensure_ascii=False)
    )


async def telegram_webhook(request: Request):
    data = await request.json()

    update = Update.de_json(
        data,
        application.bot
    )

    await application.process_update(update)

    return {"ok": True}


@app.get("/")
async def health():
    return {"status": "ok"}


@app.get("/run.jsonl", response_class=PlainTextResponse)
async def logs():
    if not os.path.exists(LOG_FILE):
        return ""

    with open(LOG_FILE, "r", encoding="utf-8") as f:
        return f.read()


application = Application.builder().token(BOT_TOKEN).build()

application.add_handler(
    MessageHandler(
        filters.TEXT & ~filters.COMMAND,
        handle_message
    )
)


@app.post("/telegram")
async def telegram_endpoint(request: Request):
    return await telegram_webhook(request)
